-- MySQL Script generated by MySQL Workbench
-- Tue Nov 10 20:29:03 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema LFDPA
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema LFDPA
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `LFDPA` DEFAULT CHARACTER SET utf8 ;
USE `LFDPA` ;

-- -----------------------------------------------------
-- Table `LFDPA`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LFDPA`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `role` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LFDPA`.`movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LFDPA`.`movie` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` MEDIUMTEXT NULL,
  `resume` LONGTEXT NULL,
  `photo` LONGTEXT NULL,
  `slug` VARCHAR(255) NULL,
  `place` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LFDPA`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LFDPA`.`post` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL,
  `content` LONGTEXT NULL,
  `date` DATETIME NULL,
  `slug` VARCHAR(255) NULL,
  `place` VARCHAR(255) NULL,
  `photo` LONGTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LFDPA`.`postcategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LFDPA`.`postcategory` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `slug` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LFDPA`.`programme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LFDPA`.`programme` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NULL,
  `slug` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LFDPA`.`moviecategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LFDPA`.`moviecategory` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `slug` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LFDPA`.`newsletter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LFDPA`.`newsletter` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NULL,
  `name` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LFDPA`.`movie_has_moviecategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LFDPA`.`movie_has_moviecategory` (
  `movie_id` INT NOT NULL,
  `moviecategory_id` INT NOT NULL,
  PRIMARY KEY (`movie_id`, `moviecategory_id`),
  INDEX `fk_movie_has_moviecategory_moviecategory1_idx` (`moviecategory_id` ASC) VISIBLE,
  INDEX `fk_movie_has_moviecategory_movie_idx` (`movie_id` ASC) VISIBLE,
  CONSTRAINT `fk_movie_has_moviecategory_movie`
    FOREIGN KEY (`movie_id`)
    REFERENCES `LFDPA`.`movie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movie_has_moviecategory_moviecategory1`
    FOREIGN KEY (`moviecategory_id`)
    REFERENCES `LFDPA`.`moviecategory` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LFDPA`.`movie_has_programme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LFDPA`.`movie_has_programme` (
  `movie_id` INT NOT NULL,
  `programme_id` INT NOT NULL,
  PRIMARY KEY (`movie_id`, `programme_id`),
  INDEX `fk_movie_has_programme_programme1_idx` (`programme_id` ASC) VISIBLE,
  INDEX `fk_movie_has_programme_movie1_idx` (`movie_id` ASC) VISIBLE,
  CONSTRAINT `fk_movie_has_programme_movie1`
    FOREIGN KEY (`movie_id`)
    REFERENCES `LFDPA`.`movie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movie_has_programme_programme1`
    FOREIGN KEY (`programme_id`)
    REFERENCES `LFDPA`.`programme` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LFDPA`.`post_has_postcategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LFDPA`.`post_has_postcategory` (
  `post_id` INT NOT NULL,
  `postcategory_id` INT NOT NULL,
  PRIMARY KEY (`post_id`, `postcategory_id`),
  INDEX `fk_post_has_postcategory_postcategory1_idx` (`postcategory_id` ASC) VISIBLE,
  INDEX `fk_post_has_postcategory_post1_idx` (`post_id` ASC) VISIBLE,
  CONSTRAINT `fk_post_has_postcategory_post1`
    FOREIGN KEY (`post_id`)
    REFERENCES `LFDPA`.`post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_has_postcategory_postcategory1`
    FOREIGN KEY (`postcategory_id`)
    REFERENCES `LFDPA`.`postcategory` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
